kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: react-app
  namespace: react-app-demo
spec:
  to:
    kind: Service
    name: react-web-argo-application
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
